/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mh' at '9/18/17 9:22 AM' with Gradle 2.9
 *
 * @author mh, @date 9/18/17 9:22 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
